### PR TITLE
Removes the diff from exception>message if expected and actual are present

### LINKED ISSUE #3: Exception message should not contain a diff if the details hash is available
Example JSON:

```json
{
  "id": "/tmp/spec.rb[1:1:1]",
  "description": "should print 'monkey salmon'",
  "full_description": "Spec Even words should print 'monkey salmon'",
  "status": "failed",
  "file_path": "/tmp/spec.rb",
  "line_number": 21,
  "run_time": 0.004723126,
  "pending_message": null,
  "metadata": {
    "location": "/tmp/spec.rb:21",
    "absolute_file_path": "/tmp/spec.rb",
    "rerun_file_path": "/tmp/spec.rb:21",
    "example_group": "Even words",
    "example_group_hierarchy": ["Spec", "Even words"],
    "shared_group_inclusion_backtrace": []
  },
  "exception": {
    "class": "RSpec::EnrichedJson::EnrichedExpectationNotMetError",
    "message": "Expected graded code block to not literally print monkey. Chances are you are using `p` or `puts` or `pp` to print the value, which is not allowed. Instead, make your code return the value programmatically.\nDiff:\n@@ -1 +1 @@\n-/^p.*monkey/\n+pp \"monkey\"\n",
    "backtrace": [
      "./gems/rspec-enriched_json-0.6.0/lib/rspec/enriched_json/expectation_helper_wrapper.rb:122:in `rescue in handle_failure'",
      "./gems/rspec-enriched_json-0.6.0/lib/rspec/enriched_json/expectation_helper_wrapper.rb:94:in `handle_failure'",
      "/tmp/spec_helper.rb:48:in `block in failure_if_literally_printing'",
      "/tmp/spec_helper.rb:46:in `foreach'",
      "/tmp/spec_helper.rb:46:in `failure_if_literally_printing'",
      "/tmp/spec.rb:23:in `block (3 levels) in <top (required)>'",
      "------------------",
      "--- Caused by: ---",
      "  Expected graded code block to not literally print monkey. Chances are you are using `p` or `puts` or `pp` to print the value programmatically.",
      "  Diff:",
      "  @@ -1 +1 @@",
      "  -/^p.*monkey/",
      "  +pp \"monkey\"",
      "  ./gems/rspec-enriched_json-0.6.0/lib/rspec/enriched_json/expectation_helper_wrapper.rb:102:in `handle_failure'"
    ]
  },
  "details": {
    "expected": {
      "class": "Regexp",
      "inspect": "/^p.*monkey/",
      "to_s": "(?-mix:^p.*monkey)"
    },
    "actual": "pp \"monkey\"\n",
    "matcher_name": "RSpec::Matchers::BuiltIn::Match",
    "original_message": "expected \"pp \\\"monkey\\\"\\n\" not to match /^p.*monkey/",
    "diffable": true
  }
}
```

### PR DESCRIPTION
**Pull request by swaathi**
Resolves #3 

### Problem

Certain matchers like `match` add the diff to `exception#message`. This is because the message is built with all [message lines](https://www.rubydoc.info/gems/rspec-core/RSpec/Core/Notifications/FailedExampleNotification#message_lines-instance_method).

Screenshot 2025-07-09 at 5 23 36 PM

### Solution

The `exception#message` is constructed by combining all the `message_lines`. So the first part of the message always contains either the custom or original message followed by "Diff:". It is safe to sub out everything that comes after "Diff:" to remove the diff from the exception message.

### Testing

Run `ruby demo.rb` and manually verify that "Diff:" is not part of any exception message.

Or test an individual spec,

```ruby
RSpec.describe "Simple match test" do
  # works with a matcher
  it "checks account statement" do
    expect("Your account balance is: -50").to match(/Your account balance is: [1-9]\d*/), "Insufficient funds"
  end

  # works when comparing booleans with a custom message
  it "truth teller" do
    expect(true).to eq(false), "Obviously not."
  end

  # works without a custom message also
  it "string and symbol checker" do
    expect("abc").to eq(:abc)
  end
end
```

Then run it using,

```ruby
rspec test.rb --format RSpec::EnrichedJson::Formatters::EnrichedJsonFormatter -r ./lib/rspec/enriched_json --out test.json
```

View the JSON output,

```
cat test.json | jq .
```

----

> [!IMPORTANT]
> Removes diff from exception messages in `EnrichedJsonFormatter` when both expected and actual values are present, with tests verifying this behavior.
> 
>   - **Behavior**:
>     - Removes diff from `exception#message` in `EnrichedJsonFormatter` if both expected and actual values are present.
>     - Handles cases with and without custom messages.
>   - **Testing**:
>     - Adds test in `diff_info_spec.rb` to verify diff removal from messages.
>     - Adds test in `verify_custom_message_spec.rb` to ensure custom messages are preserved without diffs.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=firstdraft%2Frspec-enriched_json&utm_source=github&utm_medium=referral)<sup> for b2528a0d0fccfd2cd2ee65771f949a773a666f54. You can [customize](https://app.ellipsis.dev/firstdraft/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: lib/rspec/enriched_json/expectation_helper_wrapper.rb [hunk 1]
```diff
@@ -120,7 +120,7 @@ def handle_failure(matcher, message, failure_message_method)
         details = {
           expected: Serializer.serialize_value(expected_raw),
           actual: Serializer.serialize_value(actual_raw),
-          original_message: original_message,  # Only populated when custom message overrides it
+          original_message: original_message, # Only populated when custom message overrides it
```
Comment (swaathi) [inline lib/rspec/enriched_json/expectation_helper_wrapper.rb:123]: Unrelated tiny fix

File: spec/diff_info_spec.rb [hunk 2]
```diff
@@ -45,7 +45,7 @@ def run_formatter_with_content(test_content)
       expect(output["examples"].first["details"]["diffable"]).to eq(true)
     end
 
-    it "captures the unescaped string string actual output" do
+    it "captures the unescaped string actual output" do
```
Comment (swaathi) [inline spec/diff_info_spec.rb:48]: Unrelated fix for a tiny typo

**Review by bpurinton — CHANGES_REQUESTED** [review]
I got two spec failures when testing this. Should be fixed:

```
Finished in 6.82 seconds (files took 0.10506 seconds to load)
31 examples, 2 failures

Failed examples:

rspec ./spec/verify_custom_message_spec.rb:41 # Custom message behavior verification removes diff from the custom message if expected and actual are present
rspec ./spec/diff_info_spec.rb:206 # diffable removes diff from the message if expected and actual are present
```

**Comment by swaathi** [comment]
Yeah I just noticed this. ☹️ The specs I wrote in the test work when added to `demo.rb`, but fail within the test suite. Weird!

**Comment by bpurinton** [comment]
> Yeah I just noticed this. ☹️ The specs I wrote in the test work when added to `demo.rb`, but fail within the test suite. Weird!

Maybe try to copy the format of the tests jelani used on this PR: https://github.com/firstdraft/rspec-enriched_json/pull/5/files

When I wrote specs like that on my since-closed PRs, they passed fine.

**Comment by swaathi** [comment]
> Maybe try to copy the format of the tests jelani used on this PR: https://github.com/firstdraft/rspec-enriched_json/pull/5/files
> 
> When I wrote specs like that on my since-closed PRs, they passed fine.

Read my mind! Addressed on [this comment](https://github.com/firstdraft/rspec-enriched_json/pull/9#issuecomment-3053448507).
